### ISSUE TITLE
Training with my own data

### ISSUE THREAD

**Issue by hongtaowu67** [kanezaki/rotationnet#10]
Hi there,

I want to train the rotationnet with my own data. But I cannot find the code to render my data (w/o the upright orientation assumption). I am wondering if you could provide the code for the rendering?

I am trying to render with .obj files.

Thanks!

**Comment by kanezaki** [comment]
Hi there,

I used the codes provided by Su et al. [here](https://github.com/suhangpro/mvcnn) to render multi-view images. Please also see [our repository](https://github.com/kanezaki/SHREC2017_track3) which renders multi-view images for training RotationNet.

Thanks!

**Comment by hongtaowu67** [comment]
Thanks! It works!
