### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by wd-hub** [kanezaki/rotationnet#2]
When I try to run the training operation 
./caffe-rotationnet2/build/tools/finetune_net.bin Training/rotationnet_modelnet40_case2_solver.prototxt caffe_nets/ilsvrc_2012_train_iter_310k 2>&1 | tee log.txt

I failed and the get the information
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1212 13:11:04.292500 20565 finetune_net.cpp:4] Deprecated. Use caffe train --solver=... [--weights=...] instead.
*** Check failure stack trace: ***

Is anyone who know why?

**Comment by kanezaki** [comment]
Hi there,

Thank you for your inquiry. Please try this:
$ ./caffe-rotationnet2/build/tools/caffe train -solver
Training/rotationnet_modelnet40_case2_solver.prototxt -weights
caffe_nets/ilsvrc_2012_train_iter_310k 2>&1 | tee log.txt

Best regards,
Asako

2017-12-12 14:15 GMT+09:00 wd-hub <notifications@github.com>:
