### ISSUE TITLE
About the size of ModelNet 40

### ISSUE THREAD

**Issue by yangze0930** [kanezaki/rotationnet#4]
Hi，
you mentioned that there are 12,311 object instances in the ModelNet 40 dataset in your paper. However, in your provided codes, you use the multi-view images generated in [Su et al. 2015], which only has 3,983 object instances. Could you please provide more details about the dataset. Thank you for your help.

**Comment by kanezaki** [comment]
Hi,
I used the multi-view images generated in [Su et al. 2015] for the experiment corresponding to Fig. 4, which can be reproduced by the provided codes here. For other experiments, I used the full set of ModelNet40 (consisting of 12,311 object instances). Thanks!

**Comment by yangze0930** [comment]
@kanezaki Thanks for your reply.

**Comment by kanezaki** [comment]
Just for your info, I have uploaded the scripts, images, and trained models for reproducing our best results on ModelNet10 and ModelNet40. Please check it out if you’re interested. Thanks!
