### ISSUE TITLE
I can't download pre-trained models

### ISSUE THREAD

**Issue by lh641446825** [kanezaki/rotationnet#6]
Sorry for bothering you. I can't download pre-trained models.  I got the following information.What I should do?
```
amax:~/Desktop/rotationnet$ wget https://data.airc.aist.go.jp/kanezaki.asako/pretrained_models/rotationnet_modelnet10_case2_ori2.caffemodel
--2019-04-08 16:54:23--  https://data.airc.aist.go.jp/kanezaki.asako/pretrained_models/rotationnet_modelnet10_case2_ori2.caffemodel
Resolving data.airc.aist.go.jp (data.airc.aist.go.jp)... 163.220.33.57
Connecting to data.airc.aist.go.jp (data.airc.aist.go.jp)|163.220.33.57|:443... failed: No route to host.
```

**Comment by kanezaki** [comment]
Our server is under maintenance now. Sorry for the inconvenience. 
I temporarily uploaded the pre-trained models here:
https://www.dropbox.com/s/6q0apvlhq59qko8/rotationnet_modelnet10_case2_ori2.caffemodel?dl=0
https://www.dropbox.com/s/8e03p1rj6e26y1c/rotationnet_modelnet40_case2_ori4.caffemodel?dl=0

**Comment by lh641446825** [comment]
> Our server is under maintenance now. Sorry for the inconvenience.
> I temporarily uploaded the pre-trained models here:
> https://www.dropbox.com/s/6q0apvlhq59qko8/rotationnet_modelnet10_case2_ori2.caffemodel?dl=0
> https://www.dropbox.com/s/8e03p1rj6e26y1c/rotationnet_modelnet40_case2_ori4.caffemodel?dl=0

Thanks for your reply.
