### ISSUE TITLE
About the save_scores.py

### ISSUE THREAD

**Issue by lh641446825** [kanezaki/rotationnet#7]
Sorry for bothering you. When I run the demo.sh,  I got the following information: 

>F0411 09:11:13.857249 25554 net.cpp:774] Cannot copy param 0 weights from layer 'conv1'; shape mismatch.  Source param shape is 96 3 7 7 (14112); target param shape is 96 3 11 11 (34848). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
demo.sh: line 7: 25554 Aborted                 (core dumped) python save_scores.py --center_only --gpu --model_def deploy_modelnet40_case1.prototxt --pretrained_model rotationnet_modelnet40_case2_ori4.caffemodel --input_file sample_case1_toilet_000000020.txt --output_file scores_case1_toilet_000000020.npy
Traceback (most recent call last):
  File "classify_npyfile_case1.py", line 9, in <module>
    scores_ = numpy.load(sys.argv[2])
  File "/home/anaconda3/envs/python2.7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'scores_case1_toilet_000000020.npy'

So I run the save_scores.py, the following information is:

>  Cannot copy param 0 weights from layer 'conv1'; shape mismatch.  Source param shape is 96 3 7 7 (14112);target param shape is 96 3 11 11 (34848). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

What I should do?

**Comment by kanezaki** [comment]
I noticed that I happened to have a bug in _save_scores.py_ when running _demo.sh_. Please pull the latest version and try it again. Thanks!

**Comment by lh641446825** [comment]
> I noticed that I happened to have a bug in _save_scores.py_ when running _demo.sh_. Please pull the latest version and try it again. Thanks!

Thanks for your reply. I downloaded all code again. But it doesn‘t work, the following information is the same.

**Comment by kanezaki** [comment]
I guess you downloaded _rotationnet_modelnet40_case2_ori4.caffemodel_ and renamed it as _rotationnet_modelnet40_case2.caffemodel_, right? Unfortunately, it doesn't work as it is. Please download the correct files:
https://www.dropbox.com/s/93dzh5b0ysoj5we/rotationnet_modelnet40_case1.caffemodel?dl=0
https://www.dropbox.com/s/8je31y5udn2unxa/rotationnet_modelnet40_case2.caffemodel?dl=0

This model _rotationnet_modelnet40_case2.caffemodel_ is different from the one you are using in that:
- based on the AlexNet architecture
- trained on a subset of ModelNet40
- trained under a bit different lighting condition

Plus, _rotationnet_modelnet40_case2_ori4.caffemodel_ was trained with rotated 3D models (i.e., rendered with a different camera system orientation).
Thanks!

**Comment by lh641446825** [comment]
Thank you! It works. I forgot to tell you that I downloaded the pre-trained models you said before, sorry for the inconvenience.
